CC=gcc
CFLAGS=-L/usr/include -lreadline

shells: shell.c  shell_2.c SingleCommandShell.c
##	$(CC) shell.c $(CFLAGS) -o shell
##	$(CC) shell_2.c $(CFLAGS) -o shell_2
	$(CC) SingleCommandShell.c -o SingleCommandShell
